apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  name: toxic-comment-model
spec:
  predictor:
    serviceAccountName: sa
    model:
      modelFormat:
        name: caikit
      runtime: caikit-standalone-runtime
      storageUri: s3://guardrails-detectors/models/